name: Deploy tested project to GCP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/build.yml@master
    with:
      JDK_VERSION: 17

  call-deploy:
    uses: trevorism/actions-workflows/.github/workflows/deploy.yml@master
    if: success() || failure()
    needs: [call-build, call-accept-before]
    with:
      JDK_VERSION: 17
      gcp_project: 'trevorism-action'
      gcp_project_id: '846837196321'
      version: '0-6-0'
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

  call-accept-before:
    uses: trevorism/actions-workflows/.github/workflows/accept.yml@master
    with:
      JDK_VERSION: 17

  call-accept-after:
    uses: trevorism/actions-workflows/.github/workflows/accept.yml@master
    needs: call-deploy
    with:
      JDK_VERSION: 17