name: Java CI with Gradle

on:
  push:
    branches: [ master ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Auth with google
        uses: 'google-github-actions/auth@v0'
        with:
          service_account: 'github-trevorism-gcloud@trevorism-gcloud.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/159773244195/locations/global/workloadIdentityPools/github-trevorism-gcloud-pool/providers/trevorism-gcloud-provider'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: clean build appengineStage -x test

      - name: Create secrets file
        uses: Amadevus/pwsh-script@v2
        id: script
        with:
          script: |
            Add-Content -Path .\build\staged-app\WEB-INF\classes\secrets.properties -Value 'clientId=${{ secrets.CLIENT_ID }}'
            Add-Content -Path .\build\staged-app\WEB-INF\classes\secrets.properties -Value 'clientSecret=${{ secrets.CLIENT_SECRET }}'
            Add-Content -Path .\build\staged-app\WEB-INF\classes\secrets.properties -Value 'signingKey=${{ secrets.SIGNING_KEY }}'

      - name: 'Deploy to App Engine'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          working_directory: "build/staged-app"
          deliverables: 'app.yaml'
          promote: true
          version: '0-3-0'

      - name: Acceptance test with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: acceptance

